### ISSUE TITLE
Snaptcha causing error with GraphQL API requests

### ISSUE THREAD

**Issue by dhmax88** [putyourlightson/craft-snaptcha#17]
### Describe the bug
When snaptcha plugin is enabled, making a request to graphql API responds with a template error that looks like it's a snaptcha spam response / template.

### To reproduce
Steps to reproduce the behaviour:
1. Install snaptcha
2. Send curl request to graphql API endpoint
3. View error / response in terminal

### Expected behaviour
API route shouldn't be effected by snaptcha

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-snaptcha/commit/c1e2ff5f3411a0b4b0ad18ad50e32ecf1219aec0 for the next release.

**Comment by bencroker** [comment]
Released in 3.0.4.

**Comment by leobauza** [comment]
@bencroker this seems to still be an issue if the request is `application/json`. In my app I can't change that to `application/graphql` (at least not easily). I was hoping that I could exclude the controller action using `excludeControllerAction` but that also doesn't seem to work:

```
'excludeControllerActions' => ['graphql/api'],
```

**Comment by bencroker** [comment]
The changes in https://github.com/putyourlightson/craft-snaptcha/commit/d7a9537eb8b5b43a3c2644f03c87083650cc2b8a should resolve this for you, can you please test and let me know?

**Comment by leobauza** [comment]
Hey, thanks. This doesn't resolve it I still get the same errors and when I disable Snatpcha then everything works again. 

I am not super familiar with Craft but one thing that may or may not be helpful:

Commenting this out in `SnaptchaService.php` makes stuff work

```php
if (!Craft::$app->getRequest()->getIsActionRequest()) {
    return false;
}
```

Or rather, removing the `!` but I may be misunderstanding what that is doing.

**Comment by bencroker** [comment]
Can you show me the contents of your request to the GraphQL API?

**Comment by leobauza** [comment]
My request is just `{ ping }` and I pass a the Authorization header with the token for the endpoint (I mean any request fails the same way). Works when I disable Snaptcha. Other than that we are using ApolloClient on a React app. It's not doing anything weird other than setting the Authorization header.  We also just updated from:

```
-    "putyourlightson/craft-snaptcha": "2.2.5",
+   "putyourlightson/craft-snaptcha": "3.0.5",
```

That's when the API broke for us. We used to do this in the Snatpcha config:

```
'excludedUriPatterns' => ['api'],
```

To allow the API to not be affected but that setting went away and `'excludeControllerActions' => ['graphql/api'],` didn't work.

**Comment by bencroker** [comment]
Ok I see now that you were right, `getIsActionRequest()` does indeed return `false` for GraphQL requests. I have removed it in https://github.com/putyourlightson/craft-snaptcha/commit/5c8bb085cf7b0a34deb3d1365f4b91b6aab530c0 and tested that it works, can you please confirm?

**Comment by leobauza** [comment]
Thanks, that does work 👍

**Comment by bencroker** [comment]
Great, released in 3.0.7.
